name: Purge jsDelivr
on:
  push:
    branches: [main]
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsS https://purge.jsdelivr.net/gh/zxvfc/zagdim-lang-switch-style@main/style.css
